[tool.poetry]
name = "pyln-bolt2"
version = "1.0.1.187"
description = "A pure python implementation of BOLT2"
authors = ["Rusty Russell <@rustyrussell>"]
license = "MIT"

packages = [
  { include = "pyln/spec/bolt2" },
]

[tool.poetry.dependencies]
python = "^3.7"
pyln-proto = {path = "../../pyln-proto"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
