name: CI

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  testfreebsd:
    runs-on: macos-10.15
    name: Build on FreeBSD
    env:
      DEVELOPER: 1
      VALGRIND: 0
      EXPERIMENTAL_FEATURES: 0
      COMPAT: 1
    steps:
    - uses: actions/checkout@v2
    - name: Build
      id: test
      uses: vmactions/freebsd-vm@v0.1.5
      with:
        envs: 'DEVELOPER COMPAT'
        usesh: true
        prepare: |
          pkg install -y \
            wget \
            py38-pip \
            py38-sqlite3 \
            gmake \
            git \
            python \
            autoconf \
            automake \
            libtool \
            gmp \
            bash \
            gettext \
            sqlite3 \
            curl

          pip install --user -U wheel pip mako==1.1.5 mrkd==0.1.6 mistune==0.8.4 jinja2==2.11.3 MarkupSafe==2.0.1
          ln -s /root/.local/bin/mrkd /usr/local/bin/mrkd

        run: |
          # Configure and build
          ./configure CC="$CC"
          gmake

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: clightning-${{ github.sha }}-freebsd
        path: |
          lightningd/lightningd
          cli/lightning-cli
        if-no-files-found: error
        retention-days: 7

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: clightning-${{ github.sha }}-freebsd
