name: CI FreeBSD

on: [push, pull_request]

jobs:
  testfreebsd:
    runs-on: ubuntu-22.04
    name: Build on FreeBSD
    timeout-minutes: 120
    strategy:
      fail-fast: true
      matrix:
        bitcoind-version: ["27.0"]
    steps:
    - uses: actions/checkout@v4
    - name: Build
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        mem: 4096
        prepare: |
          pkg install -y \
            bash \
            wget \
            python310 \
            gmake \
            git \
            python \
            postgresql16-server \
            autoconf \
            automake \
            libtool \
            bash \
            gettext \
            sqlite3 \
            lowdown \
            pkgconf \
            jq \
            protobuf \
            curl \
            uv \
            libffi

            python3.10 -m ensurepip
            python3.10 -m pip install --upgrade pip
            curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
            # pip install --user -U wheel pip mako==1.1.5 mistune==0.8.4 jinja2==2.11.3 MarkupSafe==2.0.1


        run: |
          PATH=/root/.local/bin:$PATH:/root/.cargo/bin; export PATH
          uv sync --all-extras --all-groups

          git clone https://github.com/lightning/bolts.git ../bolts
          # fatal: unsafe repository ('/Users/runner/work/lightning/lightning' is owned by someone else)
          git config --global --add safe.directory $GITHUB_WORKSPACE
          for d in libsodium libwally-core gheap jsmn libbacktrace lowdown; do git config --global --add safe.directory $GITHUB_WORKSPACE/external/$d; done
          git submodule update --init --recursive

          ./configure CC="$CC" --disable-valgrind
          uv run gmake
          uv run gmake install
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: clightning-${{ github.sha }}-freebsd
        path: |
          /usr/local/bin/lightningd
          /usr/local/bin/lightning-cli
          /usr/local/bin/lightning-hsmtool
          /usr/local/libexec/c-lightning
          /usr/local/share/man/man1
          /usr/local/share/man/man5
          /usr/local/share/man/man7
          /usr/local/share/man/man8
          /usr/local/share/doc/c-lightning
        if-no-files-found: error
        retention-days: 7

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: clightning-${{ github.sha }}-freebsd
