name: CI FreeBSD

on: [push, pull_request]

jobs:
  testfreebsd:
    runs-on: macos-12
    name: Build on FreeBSD
    timeout-minutes: 120
    env:
      DEVELOPER: 1
      VALGRIND: 0
      EXPERIMENTAL_FEATURES: 0
      COMPAT: 1
    steps:
    - uses: actions/checkout@v3
    - name: Build
      id: test
      uses: vmactions/freebsd-vm@v0
      with:
        envs: 'DEVELOPER COMPAT'
        usesh: true
        mem: 4096
        prepare: |
          pkg install -y \
            wget \
            py39-pip \
            py39-sqlite3 \
            gmake \
            git \
            python \
            postgresql12-server \
            autoconf \
            automake \
            libtool \
            gmp \
            bash \
            gettext \
            sqlite3 \
            lowdown \
            curl

          pip install --user -U wheel pip mako==1.1.5 mistune==0.8.4 jinja2==2.11.3 MarkupSafe==2.0.1
        run: |
          PATH=/root/.local/bin:$PATH
          git clone https://github.com/lightning/bolts.git ../bolts
          # fatal: unsafe repository ('/Users/runner/work/lightning/lightning' is owned by someone else)
          git config --global --add safe.directory $GITHUB_WORKSPACE

          # Configure and build
          ./configure CC="$CC"
          gmake
          gmake install
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: clightning-${{ github.sha }}-freebsd
        path: |
          /usr/local/bin/lightningd
          /usr/local/bin/lightning-cli
          /usr/local/bin/lightning-hsmtool
          /usr/local/libexec/c-lightning
          /usr/local/share/man/man1
          /usr/local/share/man/man5
          /usr/local/share/man/man7
          /usr/local/share/man/man8
          /usr/local/share/doc/c-lightning
        if-no-files-found: error
        retention-days: 7

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: clightning-${{ github.sha }}-freebsd
