---
name: CI Ubuntu
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['Ubuntu-22.04']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          bash -x .github/scripts/setup.sh
      - name: Build
        run: |
          set -e
          pip3 install --user pip wheel poetry
          poetry export -o requirements.txt --without-hashes
          python3 -m pip install -r requirements.txt
          ./configure --prefix=/usr
          make -j $(nproc)
          make install DESTDIR=inst RUST_PROFILE=release
          cd inst/ && tar --sort=name --owner=0 --group=0 --numeric-owner -cvaf ../clightning-v-${{ matrix.os }}.tar.xz .
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clightning-${{ github.sha }}-${{ matrix.os }}
          path: |
            clightning-v-${{ matrix.os }}.tar.xz
          if-no-files-found: error
          retention-days: 7
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: clightning-${{ github.sha }}-${{ matrix.os }}
