---
name: CI Ubuntu jammy
on: [push, pull_request]
jobs:
  smoke-test:
    name: Build on Ubuntu 22.04
    runs-on: ubuntu-22.04
    timeout-minutes: 300
    env:
      DEVELOPER: 1
      VALGRIND: 0
      EXPERIMENTAL_FEATURES: 0
      COMPAT: 1
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          bash -x .github/scripts/setup.sh

      - name: Build
        env:
          VALGRIND: ${{ matrix.VALGRIND }}
          DEVELOPER: ${{ matrix.DEVELOPER }}
          EXPERIMENTAL_FEATURES: ${{ matrix.EXPERIMENTAL_FEATURES }}
          COMPILER: ${{ matrix.COMPILER }}
          ARCH: ${{ matrix.ARCH }}
          COMPAT: ${{ matrix.COMPAT }}
          COPTFLAGS: ${{ matrix.COPTFLAGS }}
          NETWORK: ${{ matrix.NETWORK }}
          TEST_CMD: ${{ matrix.TEST_CMD }}
          TEST_GROUP_COUNT: ${{ matrix.TEST_GROUP_COUNT }}
          TEST_GROUP: ${{ matrix.TEST_GROUP }}
        run: |
          bash -x .github/scripts/build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: clightning-${{ github.sha }}-ubuntu22.04
          path: |
            /usr/local/bin/lightningd
            /usr/local/bin/lightning-cli
            /usr/local/bin/lightning-hsmtool
            /usr/local/libexec/c-lightning
            /usr/local/share/man/man1
            /usr/local/share/man/man5
            /usr/local/share/man/man7
            /usr/local/share/man/man8
            /usr/local/share/doc/c-lightning
          if-no-files-found: error
          retention-days: 7

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: clightning-${{ github.sha }}-ubuntu22.04
