---
name: CI MacOS
on: [push, pull_request]
jobs:
  testmacos:
    name: Build
    runs-on: macos-latest
    timeout-minutes: 120
    strategy:
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          export PATH="/usr/local/opt:/Users/runner/.local/bin:/Users/runner/Library/Python/3.10/bin:$PATH"

          export GROESTLCOIN_VERSION=24.0.1
          brew install wget autoconf automake libtool python@3.10 gnu-sed gettext libsodium protobuf

          (
            cd /tmp/
            wget https://github.com/Groestlcoin/groestlcoin/releases/download/v24.0.1/groestlcoin-24.0.1-x86_64-apple-darwin.tar.gz -O groestlcoin.tar.gz
            tar -xvzf groestlcoin.tar.gz
            sudo mv groestlcoin-$GROESTLCOIN_VERSION/bin/* /usr/local/bin
          )

          python3.10 -m pip install -U --user poetry==1.3.2 wheel pip
          python3.10 -m poetry install
          python3.10 -m pip install -U --user mako

          ln -s /usr/local/Cellar/gettext/0.20.1/bin/xgettext /usr/local/opt

      - name: Build
        run: |
          export PATH="/usr/local/opt:/Users/runner/.local/bin:/Users/runner/Library/Python/3.10/bin:/usr/local/opt:$PATH"
          export CFLAGS="-Wno-error -Wno-nullability-completeness -Wno-expansion-to-defined -Wno-builtin-requires-header"
          export CXXFLAGS="-Wno-error -Wno-nullability-completeness -Wno-expansion-to-defined -Wno-builtin-requires-header"

          python3.10 -m poetry run ./configure --disable-valgrind --disable-compat
          python3.10 -m poetry run make
          sudo python3.10 -m poetry run make install

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: clightning-${{ github.sha }}-macos
          path: |
            /usr/local/bin/lightningd
            /usr/local/bin/lightning-cli
            /usr/local/bin/lightning-hsmtool
            /usr/local/libexec/c-lightning
            /usr/local/share/man/man1
            /usr/local/share/man/man5
            /usr/local/share/man/man7
            /usr/local/share/man/man8
            /usr/local/share/doc/c-lightning
          if-no-files-found: error
          retention-days: 7

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: clightning-${{ github.sha }}-macos
