name: Release

on: [push, pull_request]

jobs:
  bionic:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - name: Builder image setup
        run: docker build -t cl-repro-bionic --file contrib/reprobuild/Dockerfile.bionic .
      - name: Building using the builder image
        run: docker run --rm -v $(pwd):/repo -ti cl-repro-bionic
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: clightning-${{ github.sha }}-Ubuntu-18.04.tar.xz
          path: repo/release/*Ubuntu-18.04.tar.xz
          if-no-files-found: error
          retention-days: 7
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: clightning-${{ github.sha }}-Ubuntu-18.04.tar.xz

  focal:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Builder image setup
        run: docker build -t cl-repro-focal --file contrib/reprobuild/Dockerfile.focal .
      - name: Building using the builder image
        run: docker run --rm -v $(pwd):/repo -ti cl-repro-focal
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: clightning-${{ github.sha }}-Ubuntu-20.04.tar.xz
          path: repo/release/*Ubuntu-20.04.tar.xz
          if-no-files-found: error
          retention-days: 7
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: clightning-${{ github.sha }}-Ubuntu-20.04.tar.xz

  jammy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Builder image setup
        run: docker build -t cl-repro-jammy --file contrib/reprobuild/Dockerfile.jammy .
      - name: Building using the builder image
        run: docker run --rm -v $(pwd):/repo -ti cl-repro-jammy
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: clightning-${{ github.sha }}-Ubuntu-22.04.tar.xz
          path: repo/release/*Ubuntu-22.04.tar.xz
          if-no-files-found: error
          retention-days: 7
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: clightning-${{ github.sha }}-Ubuntu-22.04.tar.xz
